version: '3'
services:
  server:
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    environment:
      APP_ENV: "development"
      APP_PORT: 5000
      MONGODB_HOSTNAME: mongodb
      MONGODB_DEFAULT_DB: db
      MONGODB_DEFAULT_COLLECTION: records
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - mongodb
      - celery
      - rabbitmq
    volumes: ['./app:/app']

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    logging: 
      driver: none

  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
  
  celery:
    build: .
    user: nobody
    environment:
      CELERY_APP_NAME: server_demo
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    command: celery worker -B -l info -A app.server_demo --concurrency=2
    depends_on:
      - rabbitmq
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"