version: '3'
services:
  server:
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    environment:
      APP_ENV: "debug"
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_HOSTNAME: mongodb
      MONGODB_DEFAULT_DB: db
      MONGODB_DEFAULT_COLLECTION: records
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    logging: 
      driver: none

  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: mypass
      RABBITMQ_HOSTNAME: rabbitmq
    ports:
        - "5673:5672"
    logging: 
      driver: none